---

<%
def digitalocean_platform(name, image)
  <<-EOS
  - name: #{name}
    driver_config:
      provider: digital_ocean
      box: digital_ocean
      box_url: https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box
      ssh_key: #{ENV['DIGITALOCEAN_SSH_PRIVATE_KEY'] || '~/.ssh/id_rsa'}
      vagrantfile_erb: test/Vagrantfile.erb
      customize:
        token: #{ENV['DIGITALOCEAN_ACCESS_TOKEN']}
        image: #{image}
        region: #{ENV['DIGITALOCEAN_REGION'] || 'sgp1'}
        size: #{ENV['DIGITALOCEAN_SIZE'] || '512mb'}
        ssh_key_name: #{ENV['DIGITALOCEAN_SSH_KEY_NAME']}
  EOS
end
%>

<%
def idcfcloud_platform(name, template_name, public_port)
  <<-EOS
  - name: #{name}
    driver_config:
      provider: cloudstack
      box: dummy
      box_url: https://github.com/schubergphilis/vagrant-cloudstack/raw/master/dummy.box
      ssh_key: #{ENV['CLOUDSTACK_SSH_PRIVATE_KEY'] || '~/.ssh/id_rsa'}
      vagrantfile_erb: test/Vagrantfile.erb
      customize:
        scheme: https
        host: compute.jp-east.idcfcloud.com
        path: /client/api
        port: 443
        api_key: #{ENV['CLOUDSTACK_API_KEY']}
        secret_key: #{ENV['CLOUDSTACK_SECRET_KEY']}
        zone_name: #{ENV['CLOUDSTACK_ZONE_NAME']}
        service_offering_name: #{ENV['CLOUDSTACK_SERVICE_OFFERING_NAME'] || 'light.S1'}
        template_name: #{template_name}
        keypair: #{ENV['CLOUDSTACK_SSH_KEYPAIR']}
        pf_open_firewall: true
        pf_ip_address: #{ENV['CLOUDSTACK_PUBLIC_IP_ADDRESS']}
        pf_public_port: #{public_port}
        pf_private_port: 22
  EOS
end
%>

<% if ENV['KITCHEN_DRIVER'] == 'digitalocean' %>
driver:
  name: digitalocean

platforms:
  - name: ubuntu1204
    driver_config:
      server_name: test-kitchen-ubuntu1204
      image: ubuntu-12-04-x64
      region: <%= ENV['DIGITALOCEAN_REGION'] || 'sgp1' %>
      size: <%= ENV['DIGITALOCEAN_SIZE'] || '512mb' %>
  - name: ubuntu1410
    driver_config:
      server_name: test-kitchen-ubuntu1410
      image: ubuntu-14-10-x64
      region: <%= ENV['DIGITALOCEAN_REGION'] || 'sgp1' %>
      size: <%= ENV['DIGITALOCEAN_SIZE'] || '512mb' %>
  - name: ubuntu1504
    driver_config:
      server_name: test-kitchen-ubuntu1504
      image: ubuntu-15-04-x64
      region: <%= ENV['DIGITALOCEAN_REGION'] || 'sgp1' %>
      size: <%= ENV['DIGITALOCEAN_SIZE'] || '512mb' %>
  - name: centos65
    driver_config:
      server_name: test-kitchen-centos65
      image: centos-6-5-x64
      region: <%= ENV['DIGITALOCEAN_REGION'] || 'sgp1' %>
      size: <%= ENV['DIGITALOCEAN_SIZE'] || '512mb' %>
  - name: centos70
    driver_config:
      server_name: test-kitchen-centos70
      image: centos-7-0-x64
      region: <%= ENV['DIGITALOCEAN_REGION'] || 'sgp1' %>
      size: <%= ENV['DIGITALOCEAN_SIZE'] || '512mb' %>
  - name: fedora22
    driver_config:
      server_name: test-kitchen-fedora22
      image: fedora-22-x64
      region: <%= ENV['DIGITALOCEAN_REGION'] || 'sgp1' %>
      size: <%= ENV['DIGITALOCEAN_SIZE'] || '512mb' %>
 <% else %>
driver:
  name: vagrant

platforms:
  - name: ubuntu1204
    driver_config:
      box: boxcutter/ubuntu1204
  - name: ubuntu1404
    driver_config:
      box: boxcutter/ubuntu1404
  - name: ubuntu1410
    driver_config:
      box: boxcutter/ubuntu1410
  - name: ubuntu1504
    driver_config:
      box: boxcutter/ubuntu1504
  - name: debian78
    driver_config:
      box: boxcutter/debian78
  - name: debian80
    driver_config:
      box: boxcutter/debian80
  - name: centos66
    driver_config:
      box: boxcutter/centos66
  - name: centos71
    driver_config:
      box: boxcutter/centos71
  - name: fedora21
    driver_config:
      box: boxcutter/fedora21
  - name: fedora22
    driver_config:
      box: boxcutter/fedora22
<%= digitalocean_platform("digitalocean_ubuntu1204", "ubuntu-12-04-x64") %>
<%= idcfcloud_platform("idcfcloud_cetos70", "CentOS 7.0 64-bit for Vagrant", 2022) %>

verifier:
  name: shell
  command: bundle exec sh -c "cd test && rake"
<% end %>

provisioner:
  name: ansible_push
  playbook: test/integration/default.yml
  ansible_config: test/integration/ansible.cfg
  verbose: vvvv
  sudo: true
  idempotency_test: true

suites:
  - name: default
